name: PR Up
on:
  workflow_dispatch: 

jobs:
 prup:
  name: PR Up
  runs-on: ubuntu-latest
  steps:
  
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Set variables
      shell: bash
      run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          branch="${branch^^}"
          echo "branch_name=${branch}" >> $GITHUB_OUTPUT
          echo "TEST" > TEST
      id: set_vars
  
    - name: Create PR 
      run: |
        test = fromJSON(secrets.TEST)
        
