name: Prepare Changes
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
jobs:
  setTarget:
    name: Get Runtime Values
    runs-on: ubuntu-latest
    outputs:
       runtimes: ${{ steps.setme.outputs.runtimes }}
    steps: 
      - name: Set variables
        shell: bash
        id: setme
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          branch="${branch^^}"
          echo "branch_name=${branch}" >> $GITHUB_ENV
          runtimes="${branch}_RUNTIMES"
          echo "runtimes=${branch}_RUNTIMES" >> $GITHUB_OUTPUT
          echo "${{ fromJSON(vars["MAIN_RUNTIMES"])[0].runtime }}"
  all-targets:
    needs: setTarget
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groupname: ${{ fromJSON(vars[needs.setTarget.outputs.runtimes]) }}
    steps:
      - name: Tell me
        run: echo "${{ matrix.groupname.runtime }}" 
